### ISSUE TITLE
how do you define the accuracy?

### ISSUE THREAD

**Issue by gslxl** [Gooong/TrajectoryMatching#1]
In your paper you compare many similarity function according to accuracy, but I can't find the defination of accuracy in paper, or I guess the value of similarity is accuracy? thank you

**Comment by Gooong** [comment]
Hi,

In the experiment we used the **TOP 5 accuracy**, which is: We retrieved k most similar candidates in Dataset. If the homologous trajectory is in the retrieved candidates, we say it is successfully matched. In our experiment we set k as 5 and compared the ratios of successfully matched trajectories as accuracies for different similarity metrics.

Thank you very much!
